### ISSUE TITLE
Syntax color highlighting differs from VSCode theme

### ISSUE THREAD

**Issue by biographie** [ghifarit53/tokyonight-vim#11]
Hey thanks for this vim port. I was wondering whether is because of the vim theme itself or might have I messed something up. I've noticed that the colors are different from those rendered in VSCode. I've attach a screenshot [here](https://imgur.com/txHHK2N.png)

**Comment by ghifarit53** [comment]
Hi, so this colorscheme was made by using @ sainnhe's sonokai colorscheme as the base. That's why it looks really different than the VSCode version. Although I've been planning on doing a total rewrite of this theme to match the VS Code version (and also my other theme daycula), I still don't have the time as for now.

**Comment by ghifarit53** [comment]
Closing

**Comment by jamischarles** [comment]
@ghifarit53 Please don't change it. I LOVE this theme.
