### ISSUE TITLE
Syntax highlighting differs from VSCode theme

### ISSUE THREAD

**Issue by Iniesta8** [ghifarit53/tokyonight-vim#23]
Hi,

at first, thanks for these theme!

I'm also using the VSCode theme (https://github.com/enkia/tokyo-night-vscode-theme) and I can recognize a big difference in terms of syntax highlighting there. For example there are much more red elements in the VIM theme than in the VSCode one.

Is it on purpose that the VIM theme and VSCode theme differ that much?

I mean, that's no problem, I just want to know. :)

**Comment by ghifarit53** [comment]
Hi @iniesta8, thanks for reaching!

Well, this theme was created when I have zero knowledge on how to make a vim colorscheme. When I found the VS Code theme, I really liked it and wanted to port it to vim, but I just don't know how to. So I ~~steal~~ borrow some code from [@sainnhe's sonokai repo](https://github.com/sainnhe/sonokai) and changing some of its color variables with the tokyonight color palettes. That's why it looks so different from the VS Code version :)

If you want the tokyonight colorscheme that [closely resembles the VS Code version](https://www.reddit.com/r/neovim/comments/mu976j/new_dark_neovim_theme_tokyonight_written_in_lua/gv4migo?utm_source=share&utm_medium=web2x&context=3) and also supports for newer neovim plugins (e.g. treesitter, lsp, telescope, etc.), I recommend you to use [folke/tokyonight.nvim](https://github.com/folke/tokyonight.nvim). The development there is also really active

**Comment by Iniesta8** [comment]
Thanks for reply!

#closed
